# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_auto_20170730_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_quantity',
            field=models.IntegerField(),
        ),
    ]
